### ISSUE TITLE
阿里云官网对于JindoDistCp Counters的说明不清楚

### ISSUE THREAD

**Issue by luoqianyi** [aliyun/alibabacloud-jindodata#104]
请问JindoDistCp Counters 是文件还是什么，我执行了JindoDistCp后没有任何事情发生，目录下没有文件，所以想问一下这是什么？

**Comment by yanbinyang** [comment]
> 请问JindoDistCp Counters 是文件还是什么，我执行了JindoDistCp后没有任何事情发生，目录下没有文件，所以想问一下这是什么？

就是mapreduce里的counter。

如果是通过hadoop jar或者jindo distcp命令行的方式使用，会显示在driver端的console上。
```
	JindoCounter
		FILES_COPIED=xxx
		BYTES_COPIED=xxx
```

如果是通过api方式使用，可以参考这篇文档 [jindo_distcp_how_to_api](https://github.com/aliyun/alibabacloud-jindodata/blob/master/docs/user/4.x/4.6.x/4.6.10/jindofs/jindo_distcp/jindo_distcp_how_to_api.md)，通过response.getCount获取结果。
