### ISSUE TITLE
jindo-core-macos-10_14-aarch64 从仓库中找不到

### ISSUE THREAD

**Issue by baisui1981** [aliyun/alibabacloud-jindodata#109]
按照文档 https://github.com/aliyun/alibabacloud-jindodata/blob/master/docs/user/4.x/4.6.x/4.6.11/jindofs/hadoop/jindosdk_ide_hadoop.md 说明

测试节点 `uname -a`
```
Darwin  22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:52 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8112 x86_64
```
执行maven compile 尝试到仓库中获取 jindo-core-macos-10_14-aarch64-4.6.11.jar ，从maven 日志中看到使用的url 为
```
https://jindodata-binary.oss-cn-shanghai.aliyuncs.com/mvn-repo/com/aliyun/jindodata/jindo-core-macos-10_14-aarch64/4.6.11/jindo-core-macos-10_14-aarch64-4.6.11.jar
```
尝试在浏览器中下载该jar包，返回以下OSS key 不存在的错误：
``` xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<RequestId>64E3005289150A333578BACB</RequestId>
<HostId>jindodata-binary.oss-cn-shanghai.aliyuncs.com</HostId>
<Key>mvn-repo/com/aliyun/jindodata/jindo-core-macos-10_14-aarch64/4.6.11/jindo-core-macos-10_14-aarch64-4.6.11.jar</Key>
<EC>0026-00000001</EC>
</Error>
```
请帮确认一下，该jar 包是否存在，之前maven 编译是没有问题，今天在另外一台新的机器上作测试，无法正常编译了

pom.xml 相关配置如下：
``` xml
<project>
 <properties>
        <jindodata.version>4.6.11</jindodata.version>
    </properties>

    <repositories>
        <!-- Add JindoData Maven Repository -->
        <repository>
            <id>jindodata</id>
            <url>https://jindodata-binary.oss-cn-shanghai.aliyuncs.com/mvn-repo/</url>
        </repository>
    </repositories>
    <dependencies>
  <dependency>
            <groupId>com.aliyun.jindodata</groupId>
            <artifactId>jindo-core</artifactId>
            <version>${jindodata.version}</version>
        </dependency>

        <!-- add jindo-core-extended-jar if you need support other platform -->
        <dependency>
            <groupId>com.aliyun.jindodata</groupId>
            <artifactId>jindosdk</artifactId>
            <version>${jindodata.version}</version>
        </dependency>
 </dependencies>
<profiles>

<profile>
            <id>dev_aarch64</id>
            <activation>
                <!--根据当前操作系统-->
                <!--inspect by: mvn enforcer:display-info-->
                <os>
                    <family>mac</family>
                    <arch>aarch64</arch>
                </os>
            </activation>
            <dependencies>
                <!-- add jindo-core-extended-jar for macos -->
                <dependency>
                    <groupId>com.aliyun.jindodata</groupId>
                    <artifactId>jindo-core-macos-10_14-aarch64</artifactId>
                    <version>${jindodata.version}</version>
                </dependency>
            </dependencies>
        </profile>
    </profiles>
</project>
```
@yanbinyang

**Comment by yanbinyang** [comment]
4.6.11的maven-repo没有支持mac aarch64，或者最近新的6.0.0或者6.0.1版本。

**Comment by yanbinyang** [comment]
> 按照文档 https://github.com/aliyun/alibabacloud-jindodata/blob/master/docs/user/4.x/4.6.x/4.6.11/jindofs/hadoop/jindosdk_ide_hadoop.md 说明
> 
> 测试节点 `uname -a`
> 
> ```
> Darwin  22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:52 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8112 x86_64
> ```
> 
> 执行maven compile 尝试到仓库中获取 jindo-core-macos-10_14-aarch64-4.6.11.jar ，从maven 日志中看到使用的url 为
> 
> ```
> https://jindodata-binary.oss-cn-shanghai.aliyuncs.com/mvn-repo/com/aliyun/jindodata/jindo-core-macos-10_14-aarch64/4.6.11/jindo-core-macos-10_14-aarch64-4.6.11.jar
> ```
> 
> 尝试在浏览器中下载该jar包，返回以下OSS key 不存在的错误：
> 
> ```
> <Error>
> <Code>NoSuchKey</Code>
> <Message>The specified key does not exist.</Message>
> <RequestId>64E3005289150A333578BACB</RequestId>
> <HostId>jindodata-binary.oss-cn-shanghai.aliyuncs.com</HostId>
> <Key>mvn-repo/com/aliyun/jindodata/jindo-core-macos-10_14-aarch64/4.6.11/jindo-core-macos-10_14-aarch64-4.6.11.jar</Key>
> <EC>0026-00000001</EC>
> </Error>
> ```
> 
> 请帮确认一下，该jar 包是否存在，之前maven 编译是没有问题，今天在另外一台新的机器上作测试，无法正常编译了
> 
> pom.xml 相关配置如下：
> 
> ```
> <project>
>  <properties>
>         <jindodata.version>4.6.11</jindodata.version>
>     </properties>
> 
>     <repositories>
>         
>         <repository>
>             <id>jindodata</id>
>             <url>https://jindodata-binary.oss-cn-shanghai.aliyuncs.com/mvn-repo/</url>
>         </repository>
>     </repositories>
>     <dependencies>
>   <dependency>
>             <groupId>com.aliyun.jindodata</groupId>
>             <artifactId>jindo-core</artifactId>
>             <version>${jindodata.version}</version>
>         </dependency>
> 
>         
>         <dependency>
>             <groupId>com.aliyun.jindodata</groupId>
>             <artifactId>jindosdk</artifactId>
>             <version>${jindodata.version}</version>
>         </dependency>
>  </dependencies>
> <profiles>
> 
> <profile>
>             <id>dev_aarch64</id>
>             <activation>
>                 
>                 
>                 <os>
>                     <family>mac</family>
>                     <arch>aarch64</arch>
>                 </os>
>             </activation>
>             <dependencies>
>                 
>                 <dependency>
>                     <groupId>com.aliyun.jindodata</groupId>
>                     <artifactId>jindo-core-macos-10_14-aarch64</artifactId>
>                     <version>${jindodata.version}</version>
>                 </dependency>
>             </dependencies>
>         </profile>
>     </profiles>
> </project>
> ```
> 
> @yanbinyang

描述有误的相关文档已经做了移除处理。

**Comment by yanbinyang** [comment]
https://github.com/aliyun/alibabacloud-jindodata/blob/master/docs/user/6.x/6.0.0/oss-maven.md

**Comment by baisui1981** [comment]
收到，发现6.x 版本中不需要针对mac OS 添加额外的jar 依赖了，谢谢

**Comment by yanbinyang** [comment]
> 收到，发现6.x 版本中不需要针对mac OS 添加额外的jar 依赖了，谢谢

如果是在macos上运行，还是需要的。
