### ISSUE TITLE
implicit depend on netbase(/etc/service file)

### ISSUE THREAD

**Issue by zizon** [aliyun/alibabacloud-jindodata#125]
jindo 6.4.0的c sdk运行时在linux环境依赖系统的/etc/service中的这一个entry:
<img width="827" alt="image" src="https://github.com/user-attachments/assets/d62f6a49-0768-40f2-8155-f00616408ebd">

在没有这个文件或者entry的情况下,
jdo_read或block至超时并返回类似
> IO error: Failed to connect Http service: http://${bucket}.cn-shanghai.oss-dls.aliyuncs.com/?dfs [RequestId] 

的错误.

大概看了下应该是sdk用的
cinatra coro_http_client在get uri未携带显式端口的时候会通过自身的fallback resolve机制最后调用glibc的 getaddrinfo-> getservbyname_r, 从而依赖lookup /etc/service 这个db.

建议sdk在使用该库是显示带上80/443等端口,避免这个隐性依赖.

另外,ubuntu上可以可以通过apt install netbase解决.

**Comment by qicosmos** [comment]
谢谢报告cinatra的这个问题，cinatra 会增加一个逻辑，没带端口的情况下显式加上80/443。
