### ISSUE TITLE
Running hadoop fs -ls oss://bucket/ with error: InvalidArgument

### ISSUE THREAD

**Issue by ideal** [aliyun/alibabacloud-jindodata#127]
Version: 6.5.0

Error message (some sensitive removed): 

2024-08-02 15:24:48,898 INFO common.FsStats: cmd=list, src=oss://{bucket}/, dst=null, size=0, parameter=null, time-in-ms=2011, version=6.5.0
ls: ErrorCode : 6400, ErrorMessage :  [RequestId]: 66AC89C0FBE5CC3938D80A5E [HostId]: {oss bucket host} [ErrorMessage]: [E1010]HTTP/1.1 400 Bad Request: <?xml version="1.0" encoding="UTF-8"?><Error>  <Code>InvalidArgument</Code>  <Message>Authorization header is invalid.</Message>  <RequestId>66AC89C0FBE5CC3938D80A5E</RequestId>  <HostId>{oss bucket host}</HostId>  <Authorization>OSS4-HMAC-SHA256 Credential=<access key>/20240802//oss/aliyun_v4_request,Signature=83a0b97ab1e4ea9bc1a8263f0b89321a91d28297cc63a6b2a8d041ebe1e0abeb</Authorization></Error> [ErrorCode]: 1010 [RequestId]: 66AC89C0FBE5CC3938D80A5E

Reference: https://help.aliyun.com/zh/oss/support/http-400-status-code#p-3bm-p20-4hv

**Comment by ideal** [comment]
> Can you show your related configurations in core-site.xml?

Like this:

```
...
    <property>
        <name>fs.AbstractFileSystem.oss.impl</name>
        <value>com.aliyun.emr.fs.oss.OSS</value>
    </property>

    <property>
        <name>fs.oss.impl</name>
        <value>com.aliyun.emr.fs.oss.JindoOssFileSystem</value>
    </property>

    <property>
        <name>fs.oss.accessKeyId</name>
        <value>{access key}</value>
    </property>

    <property>
        <name>fs.oss.accessKeySecret</name>
        <value>{secret key}</value>
    </property>

    <property>
        <name>fs.oss.endpoint</name>
        <value>{oss endpoint}</value>
    </property>
...
```

**Comment by adrian-wang** [comment]
Can you specify the endpoint that you are using?

**Comment by ideal** [comment]
> Can you specify the endpoint that you are using?

OK, it it internal private cloud env: oss-cn-wulan-env40-d01-a.inter.aliyun-inc.com

**Comment by ideal** [comment]
@adrian-wang Thanks, it works!
