### ISSUE TITLE
JindoData代码是否开源，是否支持S3访问？

### ISSUE THREAD

**Issue by czy006** [aliyun/alibabacloud-jindodata#79]
JindoData4.X 代码是否开源，是否支持S3访问？

**Comment by adrian-wang** [comment]
开源计划是有的（大概是今年），jindodata 4.3 会有 S3支持

**Comment by waterWang** [comment]
> 开源计划是有的（大概是今年），jindodata 4.3 会有 S3支持

还没有开源吗

**Comment by adrian-wang** [comment]
> > 开源计划是有的（大概是今年），jindodata 4.3 会有 S3支持
> 
> 还没有开源吗

今年才过去2个月多一点

**Comment by gaogao110** [comment]
请问 支持oss 的source吗？

**Comment by adrian-wang** [comment]
> 请问 支持oss 的source吗？

我们从最初就支持 OSS 的
