### ISSUE TITLE
jindosdk 在 Ubuntu 22.04 下存在兼容性问题

### ISSUE THREAD

**Issue by zhangkuantian** [aliyun/alibabacloud-jindodata#89]
flink on k8s 从1.13 升级到 1.15 之后，使用 flink 的官方镜像，发现jindosdk 存在兼容性问题，报错如下: 
 /opt/java/openjdk/bin/java: symbol lookup error: /tmp/libjindosdk-f179c5c1a7df993b_20221118_084921.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE

flink 官方镜像的linux版本如下:
root@flink-submit-deployment-555759df66-fvdzd:/opt/flink# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by yanbinyang** [comment]
> 暂不支持，主要是 ubuntu 22 glibc 版本中的 dlsym 符号表发生了变化，因此不支持加载低版本编译的动态库。

**Comment by yanbinyang** [comment]
> flink on k8s 从1.13 升级到 1.15 之后，使用 flink 的官方镜像，发现jindosdk 存在兼容性问题，报错如下: /opt/java/openjdk/bin/java: symbol lookup error: /tmp/libjindosdk-f179c5c1a7df993b_20221118_084921.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE
> 
> flink 官方镜像的linux版本如下: root@flink-submit-deployment-555759df66-fvdzd:/opt/flink# cat /etc/os-release PRETTY_NAME="Ubuntu 22.04.1 LTS" NAME="Ubuntu" VERSION_ID="22.04" VERSION="22.04.1 LTS (Jammy Jellyfish)" VERSION_CODENAME=jammy ID=ubuntu ID_LIKE=debian HOME_URL="https://www.ubuntu.com/" SUPPORT_URL="https://help.ubuntu.com/" BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/" PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy" UBUNTU_CODENAME=jammy


暂不支持，主要是 ubuntu 22 glibc 版本中的 dlsym 符号表发生了变化，因此不支持加载低版本编译的动态库。

**Comment by Smith-Cruise** [comment]
请问有考虑修复该问题吗

**Comment by yanbinyang** [comment]
> 请问有考虑修复该问题吗

有在考虑的，计划在新的大版本中支持

**Comment by yanbinyang** [comment]
@Smith-Cruise 在最新的4.6.4版本中已经支持了，参见https://github.com/aliyun/alibabacloud-jindodata/blob/master/docs/user/4.x/jindodata_download.md
