### ISSUE TITLE
jindodata sdk版或jindodata cache版和ossfs原理一样么

### ISSUE THREAD

**Issue by mxq-151** [aliyun/alibabacloud-jindodata#91]
如题
对文件的处理，包括缓存策略、文件上传策略等

**Comment by yanbinyang** [comment]
> 如题 对文件的处理，包括缓存策略、文件上传策略等

稍有不同，ossfs会先操作本地磁盘再操作oss，jindo-fuse会直接操作oss。
缓存上，ossfs的缓存模式是缓存在本地磁盘，jindodata的默认缓存是分布式缓存，当然也可以通过开启local-cache使用本地缓存。

另外，jindo-fuse还支持挂载oss-hdfs（jindofs服务的全托管班本），相比挂载oss，会支持更多posix语义。
相关文档可以参考：

**Comment by yanbinyang** [comment]
> 如题 对文件的处理，包括缓存策略、文件上传策略等

稍有不同，ossfs会先操作本地磁盘再访问oss，jindo-fuse会直接访问oss。

缓存模式：ossfs会缓存在本地磁盘，jindodata默认的缓存是分布式缓存，当然也可以开启local-cache使用本地缓存。

另外，jindo-fuse 还支持挂载oss-hdfs（jindofs服务的全托管版本，类似3.x版本中的jindofs block模式），兼容hdfs接口，并且支持更多posix语义。

更多文档参见：

jindo-fuse挂载oss：https://github.com/aliyun/alibabacloud-jindodata/blob/master/docs/user/4.x/4.6.x/4.6.2/oss/jindo_fuse/jindo_fuse_on_oss.md

jindo-fuse挂载oss-hdfs：https://github.com/aliyun/alibabacloud-jindodata/blob/master/docs/user/4.x/4.6.x/4.6.2/jindofs/jindo_fuse/jindo_fuse_on_dls.md

jindo-fuse使用透明缓存挂在oss：https://github.com/aliyun/alibabacloud-jindodata/blob/master/docs/user/4.x/4.6.x/4.6.2/jindofsx/jindo_fuse/jindo_fuse_on_oss.md

jindo-fuse使用透明缓存挂在oss-hdfs：https://github.com/aliyun/alibabacloud-jindodata/blob/master/docs/user/4.x/4.6.x/4.6.2/jindofsx/jindo_fuse/jindo_fuse_on_dls.md
