### ISSUE TITLE
jindo-fuse: /lib64/libfuse3.so.3: version `FUSE_3.7' not found (required by jindo-fuse)

### ISSUE THREAD

**Issue by w182757427** [aliyun/alibabacloud-jindodata#92]
jindo-fuse /data -ouri=oss://log-temp-test.oss-cn-hangzhou.aliyuncs.com/
执行上面命令的报错，是yum install -y fuse3 fuse3-devel安装的版本有问题？

**Comment by yanbinyang** [comment]
> jindo-fuse /data -ouri=oss://log-temp-test.oss-cn-hangzhou.aliyuncs.com/ 执行上面命令的报错，是yum install -y fuse3 fuse3-devel安装的版本有问题？

最新版本的 jindo-fuse（>=4.5.1） 需要 libfuse 3.7 以上版本，centos7 中 yum install 的 libfuse 应该是 3.4 版本。

**Comment by yanbinyang** [comment]
> jindo-fuse /data -ouri=oss://log-temp-test.oss-cn-hangzhou.aliyuncs.com/ 执行上面命令的报错，是yum install -y fuse3 fuse3-devel安装的版本有问题？

您可以参考对应版本的 jindo-fuse 文档对 libfuse 进行安装，如： https://github.com/aliyun/alibabacloud-jindodata/blob/master/docs/user/4.x/4.5.x/4.5.1/oss/jindo_fuse/jindo_fuse_on_oss.md
